var config = {
    version: 'BuildConference/1.0.0', // this helps to identify telemetry generated by the samples
    apiKey: 'a80c17d4-c4f3-4dc0-a661-3b8f63ab544d', // SDK DF
    apiKeyCC: '7490149c-026f-445c-bdc9-e60f7167dcda' // SDK+CC DF
};
